---
- name: also make sure ssh-agent works via sudo
  lineinfile: dest=/etc/sudoers.tmp state=present regexp='^Defaults env_keep\+\=SSH_AUTH_SOCK' line='Defaults env_keep+=SSH_AUTH_SOCK'

- name: add user to authorized_keys
  authorized_key: user={{ user }} key="{{ lookup('file', '/home/' +  user + '/.ssh/id_rsa.pub') }}"

