---
- name: update/install packages and add user
  hosts: privileged
  user: "{{ sudo_user }}"
  sudo: yes
  roles:
    - common

- name: install personal settings (shell/vim)
  hosts: personal
  user: "{{ user }}"
  roles:
    - personal
